version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/cinema_db
      - ENVIRONMENT=production
      - SECRET_KEY_ACCESS=${SECRET_KEY_ACCESS}
      - SECRET_KEY_REFRESH=${SECRET_KEY_REFRESH}
      - EMAIL_HOSTNAME=${EMAIL_HOSTNAME}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_SECURE=False
    volumes:
      - ./static:/app/static
    depends_on:
      - redis
      - celery
      - postgres
      - minio

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/cinema_db
      - ENVIRONMENT=production
      - SECRET_KEY_ACCESS=${SECRET_KEY_ACCESS}
      - SECRET_KEY_REFRESH=${SECRET_KEY_REFRESH}
      - EMAIL_HOSTNAME=${EMAIL_HOSTNAME}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_SECURE=False
    volumes:
      - ./static:/app/static
    depends_on:
      - redis
      - postgres
      - minio

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=cinema_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  redis_data:
  postgres_data:
  minio_data: 